### ISSUE TITLE
what about "hybrid BEGAN" in your paper?

### ISSUE THREAD

**Issue by BossunWang** [avishekbh/PosIX-GAN#4]
Hi,
I'm interest Fig. 7 in your paper.
According to my understanding,  you implement BEGAN model to generate image and compared with PosIX-GAN.
But how to sample z when you using BEGAN to reconstruct frontalization?
I guess you add an encoder same as the discriminator of BEGAN and not supervised using PMSE which you said in paper.
so, you have dual encoder in generator and discriminator , that named dual auto-encoder, Is that right?

**Comment by avishekbh** [comment]
Yes, you are correct. Similar encoder architecture of encoder in both generator and discriminator.
